import { ChatMessage, EmbeddingProvider, LLMProvider } from "./types";

export class GeminiProvider implements LLMProvider, EmbeddingProvider {
  private apiKey: string;

  constructor() {
    const key = process.env.GEMINI_API_KEY;
    if (!key) {
      throw new Error("GEMINI_API_KEY environment variable is required");
    }
    this.apiKey = key;
  }

  async getEmbedding(text: string): Promise<number[]> {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-embedding-001:embedContent?key=${this.apiKey}`;
    
    let retries = 5;
    let delay = 1000;

    while (true) {
      const response = await fetch(url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "models/gemini-embedding-001",
          content: {
            parts: [{ text }],
          },
          outputDimensionality: 768,
        }),
      });

      if (response.status === 429 && retries > 0) {
        console.log(`429 Too Many Requests. Retrying in ${delay}ms...`);
        await new Promise((resolve) => setTimeout(resolve, delay));
        retries--;
        delay *= 2; // exponential backoff
        continue;
      }

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Gemini embedding failed: ${response.statusText} - ${errorText}`);
      }

      const data = await response.json();
      if (!data.embedding?.values) {
        throw new Error("Invalid embedding response structure from Gemini API");
      }

      return data.embedding.values;
    }
  }

  async generateResponse(messages: ChatMessage[], systemPrompt?: string): Promise<string> {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${this.apiKey}`;

    // Map roles: system instructions go separate, assistant becomes model
    const contents = messages
      .filter((m) => m.role !== "system")
      .map((m) => ({
        role: m.role === "assistant" ? "model" : "user",
        parts: [{ text: m.content }],
      }));

    // If there is a system prompt, add it either as systemInstruction or inject it
    const systemMessage = messages.find((m) => m.role === "system");
    const activeSystemPrompt = systemPrompt || systemMessage?.content;

    const body: any = {
      contents,
    };

    if (activeSystemPrompt) {
      body.systemInstruction = {
        parts: [{ text: activeSystemPrompt }],
      };
    }

    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(body),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Gemini generation failed: ${response.statusText} - ${errorText}`);
    }

    const data = await response.json();
    const candidateText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!candidateText) {
      throw new Error("No response content generated by Gemini API");
    }

    return candidateText;
  }
}
