import { ChatMessage, LLMProvider } from "./types";

export class GroqProvider implements LLMProvider {
  private apiKey: string;
  private model: string;

  constructor() {
    const key = process.env.GROQ_API_KEY;
    if (!key) {
      throw new Error("GROQ_API_KEY environment variable is required");
    }
    this.apiKey = key;
    this.model = process.env.GROQ_MODEL || "llama-3.3-70b-specdec";
  }

  async generateResponse(messages: ChatMessage[], systemPrompt?: string): Promise<string> {
    const url = "https://api.groq.com/openai/v1/chat/completions";

    const formattedMessages = [...messages];
    if (systemPrompt && !formattedMessages.some((m) => m.role === "system")) {
      formattedMessages.unshift({ role: "system", content: systemPrompt });
    }

    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${this.apiKey}`,
      },
      body: JSON.stringify({
        model: this.model,
        messages: formattedMessages.map((m) => ({
          role: m.role,
          content: m.content,
        })),
        temperature: 0.2,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Groq API failed: ${response.statusText} - ${errorText}`);
    }

    const data = await response.json();
    const content = data.choices?.[0]?.message?.content;
    if (!content) {
      throw new Error("No content generated by Groq API");
    }

    return content;
  }
}
